### ISSUE TITLE
next-offline

### ISSUE THREAD

**Issue by vmihda** [vinissimus/next-translate#112]
Can I use this with next-offline? Could you create an example?

**Comment by aralroca** [comment]
I imagine that yes. Should not have any conflict with`next-offline` and with any other plugin.

**Comment by vmihda** [comment]
@aralroca I tried to follow the example "with the custom server" and when I built the project, I received the message "You have opted-out of Automatic Static Optimization due to getInitialProps in pages/_app". I think this was due to the fact that I used the HOCK appWithI18n. next-i18next has the same error. Are you going to fix it?

**Comment by aralroca** [comment]
> @aralroca I tried to follow the example "with the custom server" and when I built the project, I received the message "You have opted-out of Automatic Static Optimization due to getInitialProps in pages/_app". I think this was due to the fact that I used the HOC appWithI18n. next-i18next has the same error. Are you going to fix it?

Sure.  It's highly recommended to use the default way, without a custom server. You can just read the README.md and follow the steps:

* https://github.com/vinissimus/next-translate/blob/master/README.md

Or follow the `static-site` example.

Doing in this way, you can build and export your app without any problem/warning.

We also are supporting to use it with a custom server, as you saw.  The docs are in a different place than the README.md:

* https://github.com/vinissimus/next-translate/blob/master/docs/USING_CUSTOM_SERVER.md 

But doing in that way you always are going to have this warning. This is because of the custom server, not for this lib.

**Comment by aralroca** [comment]
I'm going to close this issue. If you have more doubts, you can use the spectrum chat https://spectrum.chat/next-translate

**Comment by vmihda** [comment]
@aralroca I planned to close after I do this with next-offline, but don’t worry if there are questions I’ll write
