### ISSUE TITLE
Expose fixHref as an importable function

### ISSUE THREAD

**Issue by jwmann** [vinissimus/next-translate#159]
Having the `<Link>` component is super nice but there are places where I'd like to get a string instead of an anchor element.

Is there a way you can expose the internal `fixHref` function to be used?

**Comment by aralroca** [comment]
Currently the `fixHref` is used internally and not directly exposed to the API of the library. This is why is not in the documentation. However, you can use it in this way:

```js
import fixHref from 'next-translate/_helpers/fixHref'

//...
const { t, lang } = useTranslation()
console.log(fixHref('/test', lang)) // -> /en/test
```

Perhaps we could consider to move `fixHref` and `fixAs` to the first level API `next-translate/fixHref` and `next-translate/fixAs`, because they are stable and useful.

**Comment by aralroca** [comment]
I opened a PR so after `0.16.0` you can import directly from `import fixHref from 'next-translate/fixHref'`.
