### ISSUE TITLE
currentPagesDir and finalPagesDir must be in the same root dir

### ISSUE THREAD

**Issue by wescopeland** [vinissimus/next-translate#175]
Thanks for building next-translate, I love using it so far ❤️

The following config works great:

```
  "currentPagesDir": "src/pages_",
  "finalPagesDir": "src/pages",
```

However, the below config causes errors, probably because the compiled pages are not having their import paths adjusted:

```
  "currentPagesDir": "src/pages_",
  "finalPagesDir": "pages",
```

But I think this config that isn't working makes a lot of sense from a DX standpoint. I don't want "dist" files in my "src" directory while the dev server is running.

**Comment by equinusocio** [comment]
Same issue here

**Comment by aralroca** [comment]
It make sense. This should be fixed 👍

**Comment by equinusocio** [comment]
@aralroca Do you mean in 0.17.1?

**Comment by aralroca** [comment]
@wescopeland @equinusocio In 1.0.0 we are going to deprecate both: `currentPagesDir` and `finalPagesDir`. They will be no longer necessary because instead of using a workaround to work in `pages_`, you will be able to work in the normal `pages` directory, with hotrealoading/refresh, etc. 

I did a first experimental version under `1.0.0-experimental.1` prereleased if you want to experimental. Better explained here: https://github.com/vinissimus/next-translate/issues/303


So this means that after 1.0.0 this will be automatically fixed. I don't close this issue right now due it's experimental yet. But I mention it so you know.

**Comment by aralroca** [comment]
Closing this. Both fields are removed on [1.0.0-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.1). The 1.0 will be released approximately 1-2 weeks. 😊
