### ISSUE TITLE
Build Error when using "documentLang" in TypeScript

### ISSUE THREAD

**Issue by dnepro** [vinissimus/next-translate#187]
Hi,
i don't know why i didn't get this error earlier, but using v0.17.0-canary.1 and upwards if i use `next-translate/documentLang` in the `_document.tsx` i get the following error on build:

**Console Output**:
[console.txt](https://github.com/vinissimus/next-translate/files/4702786/console.txt)

If i remove the `documentLang` this error doesn't appear.

Seems the important part is `Automatically optimizing pages .Error: Cannot find module '/Users/userx/projects/own/project/packages/project-web/i18n.json'`.

Please let me know if i can/should provide more information :)

**Comment by lone-cloud** [comment]
Same issue here. Everything works fine in `next dev` but fails on build. The weird thing is that, that file definitely exists in that location.

**Comment by aralroca** [comment]
I tried to build and export the example of this repo https://github.com/vinissimus/next-translate/tree/master/examples/static-site and I can't reproduce the same issue.

@dnepro @lone-cloud Can you provide more info? Next.js version, if you are getting this error deploying to Vercel or just doing `next build && next export`? A reproducible example would be very useful 👏

Apparently, it doesn't seem to like this:

https://github.com/vinissimus/next-translate/blob/f711246235467a503311d7efcc5340c92ad19e7f/src/documentLang.js#L3

I see in the [Next.js docs](https://nextjs.org/docs/basic-features/data-fetching#reading-files-use-processcwd) that their use `path.join(process.cwd(), 'file')` instead of `path.resolve(process.cwd() + '/file'))`. Perhaps the problem could be here...

**Comment by lone-cloud** [comment]
I'm on the latest Next.js. I'm not deploying to Vercel, but rather just building locally. The issues is reproducible on both linux and windows for me. I'm not able to resolve, nor join, to require a .json file in my project. 
I forked this project and I am able to build all of the examples without problem. At this point I believe that this bug is only reproducible in Typescript Next.js apps.

**Comment by dnepro** [comment]
Hi, i've created a small demo app [dnepro/wlt-demo](https://github.com/dnepro/wlt-demo), it's a skimmed version of my current app - and it won't "really" work because i excluded the certificates for the server.

Steps to reproduce:
1. clone the repo
2. run `lerna bootstrap` (i have it installed globally)
3. `cd packages/web` and `yarn start` ... it should build and run the server as expected
4. use the `documentLang` in `pages_/_document.tsx`
5. run `yarn start` again and the build should fail

**Comment by aralroca** [comment]
@lone-cloud @dnepro I did a fix on `0.17.1-canary.1`. Can you confirm that it works now with TypeScript?

After that, I'm going to take a look deeply on this issue https://github.com/vinissimus/next-translate/issues/88

Feel free to reopen this issue if it is still happening. I'm going to wait to release `0.17.1` after receiving your feedback about this 😊

**Comment by lone-cloud** [comment]
Nice, I can confirm that your fix worked for me. Good job!

**Comment by dnepro** [comment]
Great Job, also works for me!
¡Muchas gracias! 👍

**Comment by lone-cloud** [comment]
I did a a bit more testing and while the new implementation builds well, it didn't end up working out with my deployment process. I use https://github.com/danielcondemarin/serverless-next.js which doesn't allow an easy way to deploy a custom directory structure. The current documentLang implementation requires the i18n.json to be deployed to be able to handle SSR requests.

The boilerplatey way that I've been using continues to work because it inlines the i18n.json in the bundle:
```import i18nConfig from 'i18n.json';

// Update document language
function documentLang({ __NEXT_DATA__ }) {
  const { page } = __NEXT_DATA__;
  const [, langQuery] = page.split('/');
  const lang = i18nConfig.allLanguages.find((l) => l === langQuery);

  return lang || i18nConfig.defaultLanguage;
}```

**Comment by aralroca** [comment]
@lone-cloud thanks for contributing. I added your code on [0.17.1-canary.2](https://github.com/vinissimus/next-translate/releases/tag/0.17.1-canary.2) release.
