### ISSUE TITLE
Localized Dates and Numbers support

### ISSUE THREAD

**Issue by tifa2UP** [vinissimus/next-translate#212]
Love this repo. Are there plans to support localized dates and numbers? 

For example, I'd like `123` (English) to appear as `١٢٣` (Arabic) when I'm on the Arabic locale. 

Perhaps it could be built as a wrapper around https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString. 

Thank you!

**Comment by aralroca** [comment]
Hi @tifa2UP, for the moment there aren't plans for this. I would like to know the benefits of using this vía next-translate as a wrapper instead of directly with the native support (toLocaleString and Intl.DateTimeFormat). Maybe It can make sense for plurals... ?

Thanks for the proposal, and let's go to valorate it.

**Comment by aralroca** [comment]
I'm going to close this issue, there aren't plans to move this to the API. The way to do it is with `Intl.NumberFormat` and `Intl. DateTimeFormat`.

Example: 

```js
const formatters = {
  es: new Intl.NumberFormat("es-ES"),
  en: new Intl.NumberFormat("en-EN"),
}

t('common:variable-example', { price: formatters[lang].format(1234) })
```
