### ISSUE TITLE
next-translate ignoring defaultLanguage when upgrading to v0.17.1

### ISSUE THREAD

**Issue by HassenHichri** [vinissimus/next-translate#213]
Hi,
I upgraded my project from v0.14.3 to 0.17.1 ti use `documentLang` but now the build step doesn't generate sub-folder for default language.
my i18n.json file looks like this:
```javascript
{
  "allLanguages": ["en-en", "de-de"],
  "defaultLanguage": "de-de",
  "currentPagesDir": "pages_",
  "finalPagesDir": "pages",
  "localesPath": "locales",
  "pages": {
    "*": ["common"]
  }
}
```
with v0.14.3, next-translate will output
```
.
|-- de-de
|   `-- index.js
|-- en-en
|   `-- index.js
`-- index.js

```
while with 0.17.1, the output is
```
.
|-- en-en
|   `-- index.js
`-- index.js

```

Thank you!

**Comment by aralroca** [comment]
In  +`0.17.0` this behavior of "duplicated" default pages isn't more available. As a solution to this, there is now the `defaultLangRedirect` property.

The default pages like your `index.js` now are only in `/index.js` **or** in `/de-de/index.js` (depending on the `defaultLangRedirect` configuration), instead of  `/index.js` **and** `/de-de/index.js`.

`defaultLangRedirect:  undefined` (Your case) -> Default pages as `/my-route` without redirects.
`defaultLangRedirect: "root"` -> Default pages as `/my-route`. Redirects `/en/my-route` to `/my-route`
`defaultLangRedirect: "lang-path"` -> Default pages as `/en/my-route`. Redirects `/my-route` to `/en/my-route`

Hope it helps.

**Comment by HassenHichri** [comment]
yeah it broke `next export`  with `exportPathMap`.
I tried it out with defaultLangRedirect and it worked but for now I will just roll back and use the old workaround for `documentLang` 😅 
Thank you!
