### ISSUE TITLE
With Next.js 9.5

### ISSUE THREAD

**Issue by arnaudjnn** [vinissimus/next-translate#245]
I have the following structure in my app

pages_
--[...slug].jsx
--index.jsx

When I try to remove the index page I have the following error:
```
(node:48437) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

Let me know how can I use a unique catch-all page with the new 9.5

**Comment by aralroca** [comment]
Hi @arnaudjnn, with this:

```
pages_
└── [...slug].tsx
```

After the build step, is copying the "catch-all" to every locale:

```
pages
├── [...slug].js
├── ca
│   └── [...slug].js
├── en
│   └── [...path].js // This is the catch-all that redirects to /
└── es
    └── [...slug].js
```

And looks that they work as I expected:

![image](https://user-images.githubusercontent.com/13313058/90756743-094e5600-e2dd-11ea-961b-c3b04562bd7e.png)


Can you share the generated `pages` folder structure? And what are you expecting about this structure? This could help to solve your problem.

In principle, if there are several "catch-alls" at different levels: `/[...slug]` and `/es/[...slug]`, the "catch-all" of the root would also take care of `/es` since there is no `/es/index.js`, that is a mistake that could occur.

If you want only one "catch-all" on the root without copying it to every locale folder, is something that can be done after this feature will be implemented: https://github.com/vinissimus/next-translate/issues/169

**Comment by arnaudjnn** [comment]
Thank @aralroca
What I want is to use one only [optional catch-all routes](https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes) in the _pages folder

```bash
_pages
├── _document.js
├── _app.js
└── [[...slug]].js
```

Here is the scenarios:
```bash
_pages
├── _document.js
├── _app.js
├── [...slug].js
└── index.js
```
✅ Everything works as expected (current setup)

```bash
_pages
├── _document.js
├── _app.js
├── [[...slug]].js
└── index.js
```
❌ Error
```
Error: You cannot define a route with the same specificity as a optional catch-all route ("/en" and "/en[[...slug]]").
```

```bash
_pages
├── _document.js
├── _app.js
└── [...slug].js or [[...slug]].js
```
❌ Error
```
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

Let me know

**Comment by giovannigiordano** [comment]
It's not a bug. As @aralroca  said, you cannot use the "Optional catch all routes" as a direct child of pages folder without an index.
@arnaudjnn can you explain better the desired behavior?

**Comment by arnaudjnn** [comment]
If you read [this part](https://nextjs.org/docs/basic-features/data-fetching) of Next.js doc, now for data fetching it's better to have one dynamic route to be able to create new pages slug from the backend.

What I need is to be able to have only one page  [[...slug]] [like this](https://github.com/strapi/strapi-starter-next-corporate/blob/master/frontend/pages/%5B%5B...slug%5D%5D.js).

Currently, I'm obliged to have also one index page [like this](https://github.com/Angulaire/next-starter)
