### ISSUE TITLE
Dynamic Namespaces and Link is behaving strange in custom App.js

### ISSUE THREAD

**Issue by jawil003** [vinissimus/next-translate#246]
I used the `<DynamicNamespaces/>` and `<Link/>` Components of this Libary but they both seems to have problems with being at App Level. The Link is removing the whole Url and replaces it with its href and the DynamicNamespaces:

```
<DynamicNamespaces
      dynamic={(lang: string, ns: string) =>
        import(`../locales/${lang}/${ns}.json`).then(
          (m) => m.default
        )
      }
      namespaces={["app"]}
      fallback="Loading..."
    >
```

Is Erroring with `Cannot find module './/app.json' `.

The Link: 
```
<Link href={element.url}>
    <a>
       <span>Example</span>
    </a>
</Link>
```
Is as described above just removing domain and language prefix of the url.

Idk what I could try...

Hope someone can help me out. If Error cannot be reproduced I will probvide a Codepen.

**Comment by aralroca** [comment]
Both are consuming the i18n context. And the `_app.js` is not wrapped with the context by default. Did you try to wrap everything with [I18nProvider](https://github.com/vinissimus/next-translate#i18nprovider)?

**Comment by jawil003** [comment]
@aralroca So I just need to put `<I18nProvider/>` at Document Level? Or do I need to Provide the Data then or is this happening automatically?

**Comment by aralroca** [comment]
The `_app.js` file, after the "build step" is the same `_app.js` file that you wrote. There is an open issue in order to provide the translations here in the same way that the rest of pages: https://github.com/vinissimus/next-translate/issues/44 . However, it's quite tricky and there isn't a good solution for now.

We recommend avoiding translations on `_app.js` level right now. Providing a Layout wrapper in each page. This is not the best solution, but at least loads the necessary namespaces on each page.

Another workaround is what you are trying; loading the namespaces dynamically on the `_app.js`. But with this way, you need to provide all the necessary things:

* Wrap all the `_app.js` with `<I18nProvider lang={lang}>` - You need to extract the lang from the URL with your own logic.
* Wrap the rest with `< DynamicNamespaces>`, using the same lang 
* Inside the two wrappers you can use the rest of next-translate API: Link, Router, etc

**Comment by jawil003** [comment]
Oh okay I found the `<I18nProvider/>` and really strange behaving I really like this libary over i18next which is hard to configure etc but I don't understand the actual issue of not providing the language to the Html Level would help to access it anywhere or even evaluate by the url idk, but how is it so different of what is done in a Page? Tried with custom Providers and HTML Document level and it seems to work fine, different but fine? Maybe I can provide the code to may find a better solution for this?

**Comment by aralroca** [comment]
@jawil003 you can add the language to the Html level doing this:

**_document.js**
```js
import Document, { Html, Head, Main, NextScript } from 'next/document'
import documentLang from 'next-translate/documentLang'

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang={documentLang(this.props)}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```

Getting the **language** on `_app.js` and `_document.js` is not hard.  The problem comes from having the necessary imports with the **namespaces** of the current language.

On page level, we have one file per language (`/pages/en/my-page`, `/pages/es/my-page` ...). Thus, with the build step each page has they necessary imports:

* `/pages/en/my-page` -> `locales/en/common.json` + `locales/en/example.json`
* `/pages/es/my-page` -> `locales/es/common.json` + `locales/es/example.json`

This works really well in order to make i18n web applications totally static, that is, when doing`npm run export` it works well. 

However, `_app.js` and `_document.js` are at the top level, they cannot be within `/en/_app.js` and `/es/_app.js`... So even if we know the language, **we don't know what namespaces to import**, unless you use dynamic imports (DynamicNamespaces, what you did), or you import all the namespaces for each language.

A possible future solution would be to use `getStaticProps`, but it still doesn't have support at `_app.js` level, so for the moment, the only alternatives are the ones I have mentioned. Or create a Layout component and have it wrap around each page.

**Comment by jawil003** [comment]
So it is impossible to translate the `_app.js` static on the Server Side and I need to provide a way to translate on client side by providing the lang to the html and then get it from the attribute and then load the json file from the Provider right? That's at least how I did it but I needed to create custom components because it would be more helpful to provide a `t()` function to the Provider so that there is no need of the Trans Component anymore. But I need to evaluate that it works with `next export` as well tomorrow,
