### ISSUE TITLE
DynamicNamespaces lang parameter empty on custom 404 page. 

### ISSUE THREAD

**Issue by ystewart** [vinissimus/next-translate#261]
I used the <DynamicNamespaces/> on a custom 404 page and it seems that the lang parameter is empty which results into module import error. 
Anyone come across this issue?

**Comment by aralroca** [comment]
Internal pages as `_error.js`, `_app.js`, `_document.js` are not wrapped with the i18n provider. It's explained in the documentation, and there is an open issue here https://github.com/vinissimus/next-translate/issues/44 in order to add it in the future.

Hope this helps you: https://github.com/vinissimus/next-translate/issues/182#issuecomment-634077691

**Comment by aralroca** [comment]
@ystewart can you try [0.19.1-canary.1)](https://github.com/vinissimus/next-translate/releases/tag/0.19.1-canary.1), we are using the router locale as default when the I18nProvider doesn't have a language. Maybe you need to migrate to [0.19.0](https://github.com/vinissimus/next-translate/releases/tag/0.19.0) first. Hope it helps!

**Comment by aralroca** [comment]
@ystewart there is no need to DynamicNamespaces anymore inside 404.js and _error.js pages, you can translate it as a normal pages! This will be released on `0.19.1`  (prereleased on 0.19.1-canary.2)
