### ISSUE TITLE
Allow using .js files in translations instead of .json

### ISSUE THREAD

**Issue by alexnm2566** [vinissimus/next-translate#316]
Hi, I'd like to use .js files as locale translations, eg. "en -> common.js" where I could import some constants and use them as keys instead of manually writing key names, etc. Is this possible? Thanks 
![image](https://user-images.githubusercontent.com/58153395/98700729-f3a77480-2391-11eb-9fdc-a86ca46eee94.png)

So I don't get an error like this 
![image](https://user-images.githubusercontent.com/58153395/98700839-1174d980-2392-11eb-9c56-4b130ea7f4a5.png)

**Comment by aralroca** [comment]
@alexnm2566 We can remove the `.json` from the import to allow other formats like `.js`, however it will only work if in the `.js` file you are exporting a json with the translations in the same way than `.json`. Will this work for you? If so, we can make this fix for the next release, it's easy to do.

if this doesn't work for you, we are developing the version 1.0 of this library, and this changes a little bit, allowing to download the namespaces from whereever. You can experiment with `1.0.0-experimental.3` (It's quite experimental yet).

Instead of:

```js
{
  localesPath: 'locales'
}
```

you will be able to do this:

```js
{
  loadLocaleFrom: (locale, namespace) => import(`./locales/${locale}/${namespace}.js`).then((m) => m.default)
}
```


 Furthermore, that there is no longer any need to "build step" in 1.0 and [more advantages](https://github.com/vinissimus/next-translate/issues/303). It's probable that there are broken things, but well, if you try it and things fail, let me know and we'll fix it! Thank you!

**Comment by alexnm2566** [comment]
@aralroca Yes, thank you! The both methods will work perfectly for me

**Comment by aralroca** [comment]
@alexnm2566 Then, in the next release 0.19.5 you will be able to use it! I made a [0.19.5-canary.2](https://github.com/vinissimus/next-translate/releases/tag/0.19.5-canary.2) pre-release if you want to try it out and confirm that it works, let me know! Thank you!

**Comment by alexnm2566** [comment]
@aralroca Wow thank you very much! This is great! :) 0.19.5-canary.2 worked perfectly for me, thanks!

**Comment by aralroca** [comment]
@alexnm2566 nice, I just did the [0.19.5](https://github.com/vinissimus/next-translate/releases/tag/0.19.5) release 😜 thank you very much for reporting it, if you find how to improve the library further do not hesitate to report it!
