### ISSUE TITLE
0.19.5 version loads only default locale for all routes

### ISSUE THREAD

**Issue by alexnm2566** [vinissimus/next-translate#325]
First of all, thank you for this great library. I noticed that when upgrading to **0.19.5** version, every locale route still loads only default locale namespace. For example, if you have default "en" and go to "ru", it will still load default "en" locale.

Though in **0.19.4** this bug doesn't exist and everything works properly, maybe it has something to do with this feature when we changed to load not only .json, but also .js files? 
![image](https://user-images.githubusercontent.com/58153395/99144427-3c577a00-267f-11eb-821c-18a4fbca018c.png)

But I don't understand how this can affect library to load only default namespace

**Comment by aralroca** [comment]
@alexnm2566 I see you have closed the issue, have you found out why this was happening?

**Comment by alexnm2566** [comment]
> @alexnm2566 I see you have closed the issue, have you found out why this was happening?

Sorry I think there was a bug on my machine :D Because on other project with the same exact version it's working properly. Thanks

**Comment by aralroca** [comment]
@alexnm2566 I think it's related to this issue about `getInitialProps`: https://github.com/vercel/next.js/discussions/18396 is loading the default language because Next.js is not providing the `locale` in this case... We recommend to use `getServerSideProps` instead of `getInitialProps` meanwhile Next.js team don't fix this...

**Comment by alexnm2566** [comment]
@aralroca Apparently when I wrapped my exported page like so 
`export default connect(mapState, mapDispatch)(WithLayout(Home));` 
it was causing next-translate to build the page with gIP, but when I exported it like so
`const wrapped = WithLayout(Home);` 
`export default connect(mapState, mapDispatch)(wrapped);` 
Then it worked! Maybe with has something to do with named export or idk

**Comment by aralroca** [comment]
Yes, works as you say: If you don't provide any loader (getStaticProps, getServerSideProps, getInitialProps), it's loading a default loader:

- **getStaticProps** for almost all cases is the default one.
- **getServerSideProps** for dynamic pages ([slug], [...catchall]) because we don't have idea about getStaticPaths.
- **getInitialProps** when a HoC is detected in order to avoid conflicts because using HoC is the only case that a `getInitialProps` can be wroten by the HoC. **This is your case.**

However, these are the default loaders, if you write a loader it will be detected and will be used to load the translations.

**Comment by alexnm2566** [comment]
@aralroca Yeah this is it. Thanks you very much! :)
