### ISSUE TITLE
Architectural change around large scale applications

### ISSUE THREAD

**Issue by masoodtalha** [vinissimus/next-translate#326]
It looks like one of the biggest changes that I have to make while using Next Translate is create another folder for keeping/handling all of my NextJS pages. The library then compiles them into the pages folder which has to be git ignored. In all fairness I am not fully comfortable with this particular architecture change. 

How's it going to impact my flows when the application size increases. Are there going to be any adverse affects? 

For example losing control of your pages folder (the nucleus of how NextJS works) can lead to situation where my orchestration might get affected. Or I may not be able to extend this a lot as the app grows.

P.S. - I am specifically talking about next translate's with build feature!

Thanks

**Comment by aralroca** [comment]
@masoodtalha we are working on version 1.0.0 of this library removing this "build step", you can read more about it in this issue: https://github.com/vinissimus/next-translate/issues/303, and you can try the prerelease [1.0.0-experimental.4](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-experimental.4)

In fact, if you can try the experimental version and give feedback I would appreciate it very much, because this way we will stabilize the version by correcting possible issues.

To migrate to 1.0.0 just rename pages_ by pages and replace the build step by the Next.js plugin. 

The "build step" story comes because before i18n routing was supported in Next.js what we did in the "build step" was to create static pages with each of the languages *(as a temporal workaround to support static pages with translations)*. Now all the routing is done in the Next.js way, the "build step" only takes care of loading the translations and has lost a little bit of sense, which in version 1.0.0 we can delete the "build step" to load the translations with a webpack loader.

**Comment by aralroca** [comment]
@masoodtalha did you try the experimental version 1.0 without this "build step" and "pages_" workaround? I guess it will be released on December. Migrating will be relatively easy.

**Comment by aralroca** [comment]
Closing this. Build step is removed on [1.0.0-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.1). The 1.0 will be released in approximately 1-2 weeks. 😊
