### ISSUE TITLE
Plurals aren't displayed correctly in case of languages with multiple plurals

### ISSUE THREAD

**Issue by alex-ragin** [vinissimus/next-translate#344]
Hey,

I'm facing an issue implementing this library for some of the languages. For example, in Russian, there are more plural forms than 1 and plural and currently, it's really hard to cover these scenarios with this library.

In Russian, there are 3 groups:
![image](https://user-images.githubusercontent.com/22350298/100135496-646e8680-2e92-11eb-8191-761f448af17a.png)

But now I'm seeing that the plurals are assigned directly to the provided value, meaning there are no rules specified: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals

Example: https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals

How can we fix that?

Thanks!

**Comment by aralroca** [comment]
Hey @alex-ragin thank you to report this.

The truth is that the support we had for plurals was pretty basic. The `_0`, `_1`(etc) that we support does an **exact match of the number**, so we can do things like this:

```json
{
   "cart-message": "The cart has only {{count}} product",
   "cart-message_0": "The cart is empty",
   "cart-message_999": "The cart is full, you can't buy more products",
   "cart-message_plural": "The cart has {{count}} products",
}
```

With the change I have made on the PR, I have expanded the support. We will take advantage that we are going to take out version 1.0 to change that instead of `_plural` now is **`_other`** (breaking change). Apart from new: **`_zero`**, **`_one`**, **`_two`**, **`_few`**, **`_many`**. 

So the before example (in Russian) becomes:

```diff
{
   "cart-message": "The cart has only {{count}} product",
+   "cart-message_one": "The cart number ends with one",
   "cart-message_0": "The cart is empty",
+   "cart-message_few": "The cart number is a number like 42",
+   "cart-message_many": "The cart number is a number like 100",
   "cart-message_999": "The cart is full, you can't buy more products",
-   "cart-message_plural": "The cart has {{count}} products"
+   "cart-message_other": "The cart has {{count}} products"
}
```

I added the changes to the pre-release 0.21.0-canary.1, so if you want to start using it before the release, you can! Any other doubt / issue do not hesitate to report it, thank you very much!

**Comment by alex-ragin** [comment]
Hi @aralroca,

Thank you very much! Everything is great 🥇
