### ISSUE TITLE
TypeError: nextTranslate is not a function

### ISSUE THREAD

**Issue by elbopha** [vinissimus/next-translate#402]
Hello,

I am trying to run basic example here
https://github.com/vinissimus/next-translate/tree/master/examples/basic

And I got the error below when executing `npm run dev`
```
TypeError: nextTranslate is not a function
```

Any clues?

Regards,

**Comment by aralroca** [comment]
@elbopha You should execute it doing: `yarn example:basic` from the root of the project, because is needed to first build next-translate from repo. The `TypeError: nextTranslate is not a function` looks that the build is not done.

Another way is replacing this from the `package.json` of the example:

```diff
"dependencies": {
    "next": "10.0.3",
-    "next-translate": "link:../../",
+    "next-translate": "1.0.0",
-    "react": "link:../../node_modules/react",
+    "react": "17.0.1",
-    "react-dom": "link:../../node_modules/react-dom"
+    "react-dom": "17.0.1"
  }
```

**Comment by elbopha** [comment]
Thank you @aralroca
I did change the `package.json` and was using `"next-translate": "^0.20.2"` when I started looking at it.
I didn't think a release of less than 1 month would produce such error.

After using `"next-translate": "1.0.0"`, everything works fine.

**Comment by aralroca** [comment]
Yes, on 1.0 there are some breaking changes
