### ISSUE TITLE
Referencing webpack in next.config.js breaks nextTranslate

### ISSUE THREAD

**Issue by 1R053** [vinissimus/next-translate#448]
I want to apply webpack specific settings in nextjs due to this issue https://github.com/vercel/next.js/issues/13231

however, referencing webpack even without any further changes causes nextTranslate to only show i18nKeys instead of translated texts.

next.config.js:
```
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')([
  // '@project/components',
])
const nextTranslate = require('next-translate')

const date = new Date();

const nextConfig = {
  env: {
    NEXT_PUBLIC_APP_BUILD_TIME: date.toString(),
    NEXT_PUBLIC_APP_BUILD_TIMESTAMP: +date
  },
  webpack: function (config) {
    return config;
  }
}

module.exports = withPlugins([
  [withTM, {transpileModules: []}],
  nextTranslate,
  nextConfig
])

```

as soon as the webpack specific part is removed, it works again

**Comment by 1R053** [comment]
actually the issue was an error in withPlugin bracket usage

what works is:
```
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')([
  // '@project/components',
])
const nextTranslate = require('next-translate')

const date = new Date();

const nextConfig = {
  env: {
    NEXT_PUBLIC_APP_BUILD_TIME: date.toString(),
    NEXT_PUBLIC_APP_BUILD_TIMESTAMP: +date
  },
  webpack: function (config) {
    return config;
  }
}

module.exports = withPlugins([
    [withTM, {transpileModules: []}],
    nextTranslate,
  ],
  nextConfig
])
```

**Comment by westprophet** [comment]
My code is dont work correct. When I use t ("common: title") only the key is obtained instead of the translation

My config:
`module.exports = withPlugins(
  [
    fonts,
    [
      withOptimizedImages,
      {
        inlineImageLimit: 8192,
        imagesFolder: 'images',
        imagesName: '[name]-[hash].[ext]',
        handleImages: ['jpeg', 'png', 'svg', 'webp', 'ico', 'gif'],
        removeOriginalExtension: true,
        optimizeImages: true,
        optimizeImagesInDev: true,
        svgo: {
          plugins: [{ removeComments: false }],
        },
        mozjpeg: {
          quality: 55,
        },
        optipng: {
          optimizationLevel: 5,
        },
        pngquant: false,
        webp: {
          preset: 'default',
          quality: 55,
        },
      },
    ],
    nextTranslate,
  ],
  nextConfig
);
`

my i18n.json

`{
  "locales": [
    "en", "ru"
  ],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"]
  }
}`

My component `import React from 'react';
import PropTypes from 'prop-types';
import useTranslation from 'next-translate/useTranslation';
import s from './Header.module.scss';
import HeaderLogo from './components/HeaderLogo';

export default function Header({ className }) {
  const { t } = useTranslation('common');
  return (
    <header className={`${s.Header} ${className}`}>
      <div className={s.inner}>
        <HeaderLogo />
        <div className={s.title}>
          <h2>{t('description')}</h2>
          <h3>Podzgolovok</h3>
        </div>
        <div className={s.button}>
          <button>Download</button>
          <p>Push the button to download the app!</p>
        </div>
      </div>
    </header>
  );
}

Header.defaultProps = {
  className: '',
};

Header.propTypes = {
  className: PropTypes.string,
};
`
