### ISSUE TITLE
how to use the NEXT_LOCALE

### ISSUE THREAD

**Issue by adamramadhan** [vinissimus/next-translate#493]
hello, I need to persist the change when somebody goes to /en route or click

       # placed in components/header.tsx
       # href is empty so would not change the page, but when we move to 
       # another page it will be back to default, how to persist so it would only 
       # change when we click another locale="otherlang" ?

        <Link href="" locale="en" key="en">
          {t(`common:menuchangetodefaultinheader`)}
        </Link>

they should persist until anybody change the default language is there an example on how to use the next_locale in a nextjs project? where should it be placed? how do you guys use cookie or NEXT_lOCALE?

**Comment by aralroca** [comment]
@adamramadhan In your _app.js you can use a `useEffect` hook to register the cookie as long as the `locale !== defaultLocale`, for example.

**Comment by adamramadhan** [comment]
@aralroca can you give a code example of _app.js?

**Comment by aralroca** [comment]
Example on `useEffect`:

```js
import { useRouter } from 'next/router'

// ...
const { locale, defaultLocale } = useRouter()

useEffect(persistLocaleCookie, [locale, defaultLocale])
function persistLocaleCookie() {
  if(locale !== defaultLocale) {
     const date = new Date()
     const expireMs = 100 * 365 * 24 * 60 * 60 * 1000 // 100 days
     date.setTime(date.getTime() + expireMs)
     document.cookie = `NEXT_LOCALE =${locale};expires=${date.toUTCString()};path=/`
  }
}
```

**Comment by BjoernRave** [comment]
why is this not a default behavior? Without the `usePersistLocaleCookie` I change the language from `en` to `de` on my `/` page and, then if I navigate to `/lobbies` it switches back to `en` although the url is `http://localhost:3000/de/lobbies`. Is this intended behavior?

**Comment by aralroca** [comment]
@BjoernRave, this is part of Next.js, not Next-translate:

https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie

Next-translate since version 0.19 uses the **i18n routing of Next.js**, and all the logic is exactly the same as Next.js. The only new logic that Next-translate introduces now is to inject code inside the loaders (getStaticProps, getServerSideProps...) to download the translations that each page needs according to the current language.

By this, I mean that the reason why by default is so, it's something that wasn't discussed here in the library. Surely any suggestions on routing are best addressed to @timneutkens's [RFC](https://github.com/vercel/next.js/discussions/17078).

**Comment by felipe-aguirre** [comment]
> Example on `useEffect`:
> 
> ```js
> import { useRouter } from 'next/router'
> 
> // ...
> 
> function usePersistLocaleCookie() {
>     const { locale, defaultLocale } = useRouter()
> 
>     useEffect(persistLocaleCookie, [locale, defaultLocale])
>     function persistLocaleCookie() {
>       if(locale !== defaultLocale) {
>          const date = new Date()
>          const expireMs = 100 * 365 * 24 * 60 * 60 * 1000 // 100 days
>          date.setTime(date.getTime() + expireMs)
>          document.cookie = `NEXT_LOCALE=${locale};expires=${date.toUTCString()};path=/`
>       }
>     }
> }
> ```

This should be on the README, thanks a lot
