### ISSUE TITLE
Translation key context does not work

### ISSUE THREAD

**Issue by ZibbyKarel** [vinissimus/next-translate#611]
It seems that translation context is not working (https://www.i18next.com/translation-function/context)

**premium.json**
```json
{
  "type_MONTHLY": "monthly premium",
  "type_YEARLY": "yearly premium"
}
``` 

**component**
```tsx

const TestPage = () => {
  const { t } = useTranslation();
  return (
    <div>
        {/* DOES NOT WORK */}
        <div>{t('premium:type', { context: 'MONTHLY' })}</div>
        <div>{t('premium:type', { context: 'YEARLY' })}</div>
        {/* WORKS */}
        <div>{t('premium:type_MONTHLY')}</div>
        <div>{t('premium:type_YEARLY')}</div>
     </div>
   )
}
```

**Output**

```
premium:type
premium:type
monthly premium
yearly premium
```

**Comment by aralroca** [comment]
It does not work because this library is not i18next, is next-translate, and we support the [basics features](https://github.com/vinissimus/next-translate/blob/1.0.6/README.md), we believe that context is an expendable feature. The goal of this library is to keep it simple and light, so there are only features that we believe bring value. As you said, this feature can be replaced by:

```jsx
<div>{t(`premium:type_${context}`)}</div>
```

I close the issue. If I'm missing something and this feature brings some special value, comment it here and we will evaluate whether to reopen the issue and implement it. Anyway thanks to report it!
