### ISSUE TITLE
Plurals don't works with decimal number as 'count' 

### ISSUE THREAD

**Issue by ZibbyKarel** [vinissimus/next-translate#612]
Hi,

it seems that plurals don't work correctly if "count" variable is a decimal number.

**premium.json**

```json
{
  "purchaseTitle": {
      "one": "{{ count }} hour",
      "other": "{{ count }} hours"
  }
}
```

**Component**
```tsx
const C: React.FC = () => {
  const { t } = useTranslation()

  return (
     <>
         {/* WORKS */}
         {t('premium:purchaseTitle', { count: 1 })}
          
         {/* DOES NOT WORK*/}
         {t('premium:purchaseTitle', { count: 1.5 })}
     </>
   )
}
```

**Comment by aralroca** [comment]
@ZibbyKarel Can you report what you get and what you expect, what browser, and what language you are dealing with (since in each language the plurals are different)? Thanks 🙏

I have tried both English and Spanish in Chrome and 1.5 detects it as other.

Underneath it uses the Intl API, that's why I ask which browser you use:

```js
const pluralRules = new Intl.PluralRules('en')
console.log(pluralRules.select(1.5)) // other

**Comment by ZibbyKarel** [comment]
@aralroca HI. Thanks for quick response. It made me realize I have wrong plural forms in cs-CZ json (I have reported en json for some reason 😢). Sorry for this and I am closing the issue.
