### ISSUE TITLE
next-translate doesn't work with next export

### ISSUE THREAD

**Issue by fr-irene** [vinissimus/next-translate#617]
Hi, I'm adding next-translate package v1.0.7 to my next app.
And for build command, I do `next build && next export`.

I got this error when building.
```
Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
    at exportApp (/app/node_modules/next/dist/export/index.js:14:296)
error Command failed with exit code 1.
```

**Comment by aralroca** [comment]
@fr-irene Since version +0.19 of next-translate all the routing part is handled by Next.js and not by the library. One of the things that is still not supported, as commented [here](https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation), is next export:

> Note that Internationalized Routing does not integrate with next export as next export does not leverage the Next.js routing layer. Hybrid Next.js applications that do not use next export are fully supported.

I hope that from Next core they give support, now the routing is no longer the responsibility of this library and it would have to be solved directly in Next core. So I close the issue. Thanks anyway for reporting it
