### ISSUE TITLE
Problem:: Can get addition value from Component in _app.js

### ISSUE THREAD

**Issue by zeing** [vinissimus/next-translate#643]
I have 1 page 
```
// pages/admin.jsx
const AdminDashboard = () => <div>Test</div>

export default AdminDashboard

AdminDashboard.auth = {
  role: "admin",
  loading: <AdminLoadingSkeleton/>,
  unauthorized: "/login-with-different-user" // redirect to this url
}
```
And _app.js
```
function MyApp({ Component, pageProps}) {
  console.log(Component.auth) //undefined
}
export default MyApp
```
I can't get `auth` when I use `next-translate` (install in next.config.js)

**Comment by zeing** [comment]
I use https://github.com/vinissimus/next-translate#appwithi18n for use it

**Comment by aralroca** [comment]
@zeing take a look at https://github.com/vinissimus/next-translate/blob/master/docs/hoist-non-react-statics.md 

By default we do not copy statics since doing it right implies adding several kb that we do not want to add by default. Adding an alternative like hoist-non-react-statics should solve your problem.

**Comment by zeing** [comment]
> @zeing take a look at https://github.com/vinissimus/next-translate/blob/master/docs/hoist-non-react-statics.md
> 
> By default we do not copy statics since doing it right implies adding several kb that we do not want to add by default. Adding an alternative like hoist-non-react-statics should solve your problem.

thank you so much
