### ISSUE TITLE
How to use next-translate in helper files

### ISSUE THREAD

**Issue by hspotted** [vinissimus/next-translate#657]
Until now i have an application that uses react-hook-forms, nextjs and yup. My yup schema files are separated of main component to code organization.
However, by a requirement of the customer we needed to implement multilanguage support. Was very easy to implement in components, but, in helper methods and for example this yup.schema files was impossible because i cannot use useTranslate on them.

In this cases, how can i perform translation?

**Comment by aralroca** [comment]
It's done with a hook (`useTranslation`) because underneath it uses the [useContext](https://reactjs.org/docs/hooks-reference.html#usecontext) to access the context both on the server and in the browser. Just like accessing a React context from a helper cannot be done, it has the same restriction.

You can do that the helpers don't return the translation and return the namespace with the key. 

```jsx
function helperExample(isAdmin) {
  if(isAdmin) return { namespace: 'admin', key: ''description }
}
```


Or use hooks instead of helpers.
