### ISSUE TITLE
Doesn't work with Static Export

### ISSUE THREAD

**Issue by siamekanto19** [vinissimus/next-translate#706]
Whenever I use Next Translate and try to Statcally Export the Application with ``next-export`` command, I get a error message saying ``i18n is not compatible with Next Export``.
Static Export is necessary for my use case as I want to serve the  static frontend from my backend server that is written in another langaage. I can't have a nextjs server running to serve the frontend. 
I guess this should be possible by just generating separate pages and routes for each of the locale at build time and export normally as all other Statically Exported Applications.

**Comment by aralroca** [comment]
It remains for the Next.js team to implement it in their core. All the routing of i18n is not in this library, but it is the core of Next.js:

https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation

The logic of this library is the i18n part of the page translations and not the routing (which currently does not support next export). The best thing to do would be to report it directly in Next.js so that they see that it is a feature that many people need to be implemented.

**Comment by vlad-dewitt** [comment]
@aralroca, @aukgit, so what's the point of your library anyway? remove it since it doesn't work with static export. It has no usefulness and is just superfluous

**Comment by aralroca** [comment]
Next-translate facilitates the translation of texts in Next.js pages but [i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing) is part of Next.js core, if you want it to be supported with [`next export`](https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation) you have to ask for it in the Next.js repository not here.
