### ISSUE TITLE
useTranslation hook return object is not memoized

### ISSUE THREAD

**Issue by richardrobberse** [vinissimus/next-translate#818]
The return object of the `useTranslation` hook is not memoized, which means it'll be a "new" object on every render.
This is especially an issue when the `t` function is included in the dependency array of `useMemo`, `useCallback` etc.

It can easily be reproduced like this:
```typescript
import useTranslation from 'next-translate/useTranslation'
import { useMemo, useState } from 'react'
export const UseTranslationRerender: React.FC<{}> = () => {
  const { t } = useTranslation('myroofs')
  const [someValue, setSomeValue] = useState(false)
  useMemo(() => {
    console.log('useMemo')
  }, [t])
  return <button onClick={() => setSomeValue((prev) => !prev)}>Change State</button>
}
```

By the looks of it the object can be memoized based on the namespace.

**Comment by aralroca** [comment]
https://github.com/vinissimus/next-translate/pull/743

**Comment by aralroca** [comment]
You can try now the [1.3.6-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.3.6-canary.1) with this change

**Comment by richardrobberse** [comment]
@aralroca looks good to me.

**Comment by gurkerl83** [comment]
@aralroca Memoizing the t-function seems reasonable. I tried the canary 1 version referenced, but it seems it does not precisely provide what is necessary. I think the ctx-object should not be part of the dependable array; maybe ctx.lang can be allowed, but the entire ctx-object does not work.

I removed the ctx-object locally because page exit transitions still were not working with canary 1. 

Page exit transitions due to a route change mean that a component animates out; the past translations have to stay loaded even when Next loads the new page. 

Page transitions are "global"; we can not put all page-translations mapping in a common namespace. The page exit transitions are not working because the context has already changed during the route change; mounted components need to keep their translation until the component is unmounted.

```
export default function useTranslation(defaultNS?: string): I18n {
  const ctx = useContext(I18nContext)
  return useMemo(
    () => ({
      ...ctx,
      t: wrapTWithDefaultNs(ctx.t, defaultNS),
    }),
    [ctx, defaultNS] => remove ctx here !!!
  )
}
```

Thx!

**Comment by aralroca** [comment]
Thanks @gurkerl83, feel free to PR!

**Comment by gurkerl83** [comment]
@aralroca I have provided a PR for the problem of not losing translations within page exit transitions. See the commit message for more details. The PR baseline is the canary branch. 

https://github.com/vinissimus/next-translate/pull/829

Thx!

**Comment by aralroca** [comment]
Thanks for your contribution @gurkerl83, I prerelease your change to [1.3.6-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.3.6-canary.3). 

I hope it works correctly now 😊. If so, I will soon make the release.

**Comment by gurkerl83** [comment]
@aralroca Tested the canary release, works so far!
